# Highlighted paper - shown prominently on Research page
- id: doi:10.17912/micropub.biology.002018
  type: paper
  description: >
    Neurod2 deficiency prevents neural progenitor cells exiting the cell cycle and differentiating,
    predisposing the _Xenopus laevis_ tadpole brain to hyper-excitability.
  image: images/Banerjee23.jpg
  buttons:
    - type: paper
      link: https://doi.org/10.17912/micropub.biology.002018
    - type: source
      text: PubMed
      link: https://pubmed.ncbi.nlm.nih.gov/41815199/
  tags:
    - DEE
    - CRISPR
    - neuroscience
# 2026
- id: pubmed:41948612

# 2025
- id: pubmed:41104769
- id: pubmed:40819286

# 2024
- id: pubmed:39317670
- id: pubmed:38788202

# 2015
- id: pubmed:27499864

# 2014
- id: pubmed:24823862

# 2013
- id: pubmed:23981117

# 2012
- id: pubmed:22956108
- id: pubmed:22947425

# 2011
- id: pubmed:21896182
- id: pubmed:21509899
- id: pubmed:20969978

# 2009
- id: pubmed:19681139
- id: pubmed:19322766
- id: pubmed:19280606

# 2008
- id: pubmed:18570684

# 2007
- id: pubmed:17320068

# 2006
- id: pubmed:16938438

# 2003
- id: pubmed:12967562
- id: pubmed:12622731
- id: pubmed:12557213

# 2002
- id: pubmed:11934154
