- id: doi:10.17912/micropub.biology.002018
  type: paper
  description: >
    Neurod2 deficiency prevents neural progenitor cells exiting the cell cycle and differentiating,
    predisposing the _Xenopus laevis_ tadpole brain to hyper-excitability.
  image: images/Banerjee23.jpg
  buttons:
    - type: paper
      link: https://doi.org/10.17912/micropub.biology.002018
    - type: source
      text: PubMed
      link: https://pubmed.ncbi.nlm.nih.gov/41815199/
  tags:
    - DEE
    - CRISPR
    - neuroscience
